import Foundation
import GRDB
import VisionCore

struct StudyPlanItem: Codable, Identifiable, FetchableRecord, PersistableRecord {
    static let databaseTableName = "studyPlanItem"
    var id: String
    var planId: String
    var dayOffset: Int
    var topicId: String?
    var activityType: EduPlanActivityType
    var targetCount: Int
    var rationale: String
    var completedAt: Date?
}

struct StudyPlan: Codable, Identifiable, FetchableRecord, PersistableRecord {
    static let databaseTableName = "studyPlan"
    var id: String
    var documentId: String?
    var examDate: Date?
    var generatedAt: Date
    var weekStartAt: Date
}

struct StudySession: Codable, Identifiable, FetchableRecord, PersistableRecord {
    static let databaseTableName = "studySession"
    var id: String
    var documentId: String?
    var topicId: String?
    var activityType: EduPlanActivityType
    var planItemId: String?
    var startedAt: Date
    var endedAt: Date?
    var confidenceRating: Int?
}

/// Real local storage for generated weekly study plans and study sessions
/// — GRDB port of StudyPlanDbHelper.kt. Plans are generated by
/// `StudyPlanGenerator` (deterministic, rules-based, never AI-authored,
/// same as desktop); sessions record real start/complete timestamps and
/// a real self-reported confidence rating, used to compute a real
/// before/after mastery delta (see `StudySessionManager`).
///
/// Android's own `currentPlan` (most recent plan whose 7-day window
/// covers a given time) is NOT ported — genuinely unused even in
/// Android's own codebase, nothing there calls it either, matching the
/// same reasoning Phase 12 used to drop `getWeakTopics`/`getStrongTopics`.
/// `StudyPlanActivity.kt` never auto-loads an existing plan on open; this
/// screen matches that exactly, starting blank until a fresh "Generate
/// weekly plan" tap.
final class StudyPlanStore: ObservableObject {
    private let dbQueue: DatabaseQueue
    init(dbQueue: DatabaseQueue = AppDatabase.shared) { self.dbQueue = dbQueue }

    @discardableResult
    func createPlan(documentId: String?, examDate: Date?, weekStartAt: Date, items: [GeneratedPlanItem]) throws -> StudyPlan {
        let planId = UUID().uuidString
        let now = Date()
        let plan = StudyPlan(id: planId, documentId: documentId, examDate: examDate, generatedAt: now, weekStartAt: weekStartAt)
        try dbQueue.write { db in
            try plan.insert(db)
            for item in items {
                try StudyPlanItem(
                    id: UUID().uuidString, planId: planId, dayOffset: item.dayOffset, topicId: item.topicId,
                    activityType: item.activityType, targetCount: item.targetCount, rationale: item.rationale, completedAt: nil
                ).insert(db)
            }
        }
        return plan
    }

    func getPlan(_ id: String) throws -> (plan: StudyPlan, items: [StudyPlanItem])? {
        try dbQueue.read { db in
            guard let plan = try StudyPlan.fetchOne(db, key: id) else { return nil }
            let items = try StudyPlanItem.filter(Column("planId") == id).order(Column("dayOffset").asc).fetchAll(db)
            return (plan, items)
        }
    }

    func markItemCompleted(_ itemId: String) throws {
        try dbQueue.write { db in
            try db.execute(sql: "UPDATE studyPlanItem SET completedAt = ? WHERE id = ?", arguments: [Date(), itemId])
        }
    }

    @discardableResult
    func startSession(documentId: String?, topicId: String?, activityType: EduPlanActivityType, planItemId: String?) throws -> StudySession {
        let session = StudySession(id: UUID().uuidString, documentId: documentId, topicId: topicId, activityType: activityType, planItemId: planItemId, startedAt: Date(), endedAt: nil, confidenceRating: nil)
        try dbQueue.write { db in try session.insert(db) }
        return session
    }

    @discardableResult
    func completeSession(_ id: String, confidenceRating: Int?) throws -> StudySession? {
        try dbQueue.write { db in
            try db.execute(sql: "UPDATE studySession SET endedAt = ?, confidenceRating = ? WHERE id = ?", arguments: [Date(), confidenceRating, id])
        }
        return try getSession(id)
    }

    func getSession(_ id: String) throws -> StudySession? {
        try dbQueue.read { db in try StudySession.fetchOne(db, key: id) }
    }
}
